# Generated by Django 4.1 on 2023-01-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
